services:
  auth-service:
    build: .
    container_name: spring-idp
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
